### ISSUE TITLE
Request for trained model

### ISSUE THREAD

**Issue by AtmaHou** [mood2jam/artm-github#3]
Hi,
I am a PhD of Harbin Institute of Technology. 

Your paper provided interesting methods and insight to the cluster task.
So, we are now working on a paper following it~

We require your trained ARTM model as our prior knowledge. 

If possible, could you send us the trained model file for dataset "MNIST", "CIFAR10", and "FASHIONMNIST."?
（If the file is too large, you can transfer them through: https://wetransfer.com/）

I am looking forward to your response:)

Sincerely,
Atma

**Comment by mood2jam** [comment]
Hi Atma,

We are eventually planning on getting pre-trained models up with our code (it will probably happen in the next version). In the meantime, feel free to reproduce our results yourself. If you look at the "best" folder in our repository it has the best hyper-parameters for "MNIST", "CIFAR10", and "FASHIONMNIST". 

Let us know if you have any more questions!

Jamison

**Comment by AtmaHou** [comment]
> Hi Atma,
> 
> We are eventually planning on getting pre-trained models up with our code (it will probably happen in the next version). In the meantime, feel free to reproduce our results yourself. If you look at the "best" folder in our repository it has the best hyper-parameters for "MNIST", "CIFAR10", and "FASHIONMNIST".
> 
> Let us know if you have any more questions!
> 
> Jamison

Thanks a lot for the effort!
